server:
  port: 10000
spring:
  application:
    name: center-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ningyun00/ccs.git
          search-paths: ${spring.application.name}
eureka:
  client:
    registerWithEureka: false # 不注册到eureka
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:10000/center-service/
